### ISSUE TITLE
Panel not work

### ISSUE THREAD

**Issue by AlejandroOteroFreire** [VagnerDomingues/docsify-example-panels#12]
Hi, I've use the example code but panel not render.

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/37369890/99075366-1e631a00-2598-11eb-9c9f-f60379e58b52.png">

This is the md:
`# APIS

> APIS.

  (...) - Awesome title

  (...) - Awesome explanation

  (...) - Awesome example

`

**Comment by aaaaaAndy** [comment]
There is one space before 'panels', you should check your code.

**Comment by jwillmer** [comment]
fix works, thank you!

**Comment by superchango2017** [comment]
I can't get the panels to work:

```
## Panels

<!-- panels:start -->

Awesome div wrapper

<!-- panels:end -->
```

Index.html:

...
  </script>
  
  <script src="https://cdn.jsdelivr.net/npm/docsify@4"></script>
  
  <script src="https://cdn.jsdelivr.net/npm/docsify-example-panels"></script>
</body>
</html>

Not sure what is wrong. Thanks,

**Comment by VagnerDomingues** [comment]
are you creating the left and right panels between 'start and end' calls?
```
<!-- div:left-panel -->
content that shows up on left panel

<!-- div:right-panel -->
content that shows up on right panel
```

also, it is for desktop use only, below 1286px wide the panels stacks folowing a normal markdown structure to be readable and concise on mobile devices.
